version: "3.9"
services:
  koala-worker:
    build:
      context: .
      dockerfile: deploy/Dockerfile.worker

  koala-orchestrator:
    build:
      context: .
      dockerfile: deploy/Dockerfile.orchestrator
    depends_on:
      - koala-worker
    ports:
      - "6705:6705"
    volumes:
      - ./configs/koala.yaml:/app/configs/koala.yaml:ro
