// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: koala_inference.proto

package inferencev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	InferenceWorker_AnalyzeFrame_FullMethodName = "/koala.inference.v1.InferenceWorker/AnalyzeFrame"
	InferenceWorker_AnalyzeBatch_FullMethodName = "/koala.inference.v1.InferenceWorker/AnalyzeBatch"
	InferenceWorker_WorkerHealth_FullMethodName = "/koala.inference.v1.InferenceWorker/WorkerHealth"
)

// InferenceWorkerClient is the client API for InferenceWorker service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InferenceWorkerClient interface {
	AnalyzeFrame(ctx context.Context, in *FrameRequest, opts ...grpc.CallOption) (*FrameResponse, error)
	AnalyzeBatch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error)
	WorkerHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type inferenceWorkerClient struct {
	cc grpc.ClientConnInterface
}

func NewInferenceWorkerClient(cc grpc.ClientConnInterface) InferenceWorkerClient {
	return &inferenceWorkerClient{cc}
}

func (c *inferenceWorkerClient) AnalyzeFrame(ctx context.Context, in *FrameRequest, opts ...grpc.CallOption) (*FrameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FrameResponse)
	err := c.cc.Invoke(ctx, InferenceWorker_AnalyzeFrame_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceWorkerClient) AnalyzeBatch(ctx context.Context, in *BatchRequest, opts ...grpc.CallOption) (*BatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchResponse)
	err := c.cc.Invoke(ctx, InferenceWorker_AnalyzeBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *inferenceWorkerClient) WorkerHealth(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, InferenceWorker_WorkerHealth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InferenceWorkerServer is the server API for InferenceWorker service.
// All implementations must embed UnimplementedInferenceWorkerServer
// for forward compatibility.
type InferenceWorkerServer interface {
	AnalyzeFrame(context.Context, *FrameRequest) (*FrameResponse, error)
	AnalyzeBatch(context.Context, *BatchRequest) (*BatchResponse, error)
	WorkerHealth(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedInferenceWorkerServer()
}

// UnimplementedInferenceWorkerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInferenceWorkerServer struct{}

func (UnimplementedInferenceWorkerServer) AnalyzeFrame(context.Context, *FrameRequest) (*FrameResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeFrame not implemented")
}
func (UnimplementedInferenceWorkerServer) AnalyzeBatch(context.Context, *BatchRequest) (*BatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeBatch not implemented")
}
func (UnimplementedInferenceWorkerServer) WorkerHealth(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WorkerHealth not implemented")
}
func (UnimplementedInferenceWorkerServer) mustEmbedUnimplementedInferenceWorkerServer() {}
func (UnimplementedInferenceWorkerServer) testEmbeddedByValue()                         {}

// UnsafeInferenceWorkerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InferenceWorkerServer will
// result in compilation errors.
type UnsafeInferenceWorkerServer interface {
	mustEmbedUnimplementedInferenceWorkerServer()
}

func RegisterInferenceWorkerServer(s grpc.ServiceRegistrar, srv InferenceWorkerServer) {
	// If the following call panics, it indicates UnimplementedInferenceWorkerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InferenceWorker_ServiceDesc, srv)
}

func _InferenceWorker_AnalyzeFrame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FrameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceWorkerServer).AnalyzeFrame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceWorker_AnalyzeFrame_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceWorkerServer).AnalyzeFrame(ctx, req.(*FrameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceWorker_AnalyzeBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceWorkerServer).AnalyzeBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceWorker_AnalyzeBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceWorkerServer).AnalyzeBatch(ctx, req.(*BatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InferenceWorker_WorkerHealth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InferenceWorkerServer).WorkerHealth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InferenceWorker_WorkerHealth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InferenceWorkerServer).WorkerHealth(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InferenceWorker_ServiceDesc is the grpc.ServiceDesc for InferenceWorker service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InferenceWorker_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "koala.inference.v1.InferenceWorker",
	HandlerType: (*InferenceWorkerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeFrame",
			Handler:    _InferenceWorker_AnalyzeFrame_Handler,
		},
		{
			MethodName: "AnalyzeBatch",
			Handler:    _InferenceWorker_AnalyzeBatch_Handler,
		},
		{
			MethodName: "WorkerHealth",
			Handler:    _InferenceWorker_WorkerHealth_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "koala_inference.proto",
}
