// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: koala_inference.proto

package inferencev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         float32                `protobuf:"fixed32,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        float32                `protobuf:"fixed32,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BBox) Reset() {
	*x = BBox{}
	mi := &file_koala_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BBox) ProtoMessage() {}

func (x *BBox) ProtoReflect() protoreflect.Message {
	mi := &file_koala_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BBox.ProtoReflect.Descriptor instead.
func (*BBox) Descriptor() ([]byte, []int) {
	return file_koala_inference_proto_rawDescGZIP(), []int{0}
}

func (x *BBox) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BBox) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BBox) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *BBox) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type Detection struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CameraId        string                 `protobuf:"bytes,1,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	ZoneId          string                 `protobuf:"bytes,2,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Label           string                 `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	Confidence      float32                `protobuf:"fixed32,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Bbox            *BBox                  `protobuf:"bytes,5,opt,name=bbox,proto3" json:"bbox,omitempty"`
	TimestampUnixMs int64                  `protobuf:"varint,6,opt,name=timestamp_unix_ms,json=timestampUnixMs,proto3" json:"timestamp_unix_ms,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Detection) Reset() {
	*x = Detection{}
	mi := &file_koala_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Detection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Detection) ProtoMessage() {}

func (x *Detection) ProtoReflect() protoreflect.Message {
	mi := &file_koala_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Detection.ProtoReflect.Descriptor instead.
func (*Detection) Descriptor() ([]byte, []int) {
	return file_koala_inference_proto_rawDescGZIP(), []int{1}
}

func (x *Detection) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *Detection) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *Detection) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *Detection) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Detection) GetBbox() *BBox {
	if x != nil {
		return x.Bbox
	}
	return nil
}

func (x *Detection) GetTimestampUnixMs() int64 {
	if x != nil {
		return x.TimestampUnixMs
	}
	return 0
}

type FrameRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	RequestId        string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CameraId         string                 `protobuf:"bytes,2,opt,name=camera_id,json=cameraId,proto3" json:"camera_id,omitempty"`
	ZoneId           string                 `protobuf:"bytes,3,opt,name=zone_id,json=zoneId,proto3" json:"zone_id,omitempty"`
	Frame            []byte                 `protobuf:"bytes,4,opt,name=frame,proto3" json:"frame,omitempty"`
	CapturedAtUnixMs int64                  `protobuf:"varint,5,opt,name=captured_at_unix_ms,json=capturedAtUnixMs,proto3" json:"captured_at_unix_ms,omitempty"`
	// contract_version identifies the proto schema version. Must be "1".
	ContractVersion string `protobuf:"bytes,6,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FrameRequest) Reset() {
	*x = FrameRequest{}
	mi := &file_koala_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameRequest) ProtoMessage() {}

func (x *FrameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koala_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameRequest.ProtoReflect.Descriptor instead.
func (*FrameRequest) Descriptor() ([]byte, []int) {
	return file_koala_inference_proto_rawDescGZIP(), []int{2}
}

func (x *FrameRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *FrameRequest) GetCameraId() string {
	if x != nil {
		return x.CameraId
	}
	return ""
}

func (x *FrameRequest) GetZoneId() string {
	if x != nil {
		return x.ZoneId
	}
	return ""
}

func (x *FrameRequest) GetFrame() []byte {
	if x != nil {
		return x.Frame
	}
	return nil
}

func (x *FrameRequest) GetCapturedAtUnixMs() int64 {
	if x != nil {
		return x.CapturedAtUnixMs
	}
	return 0
}

func (x *FrameRequest) GetContractVersion() string {
	if x != nil {
		return x.ContractVersion
	}
	return ""
}

type FrameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelVersion  string                 `protobuf:"bytes,1,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	Detections    []*Detection           `protobuf:"bytes,2,rep,name=detections,proto3" json:"detections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FrameResponse) Reset() {
	*x = FrameResponse{}
	mi := &file_koala_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FrameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FrameResponse) ProtoMessage() {}

func (x *FrameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koala_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FrameResponse.ProtoReflect.Descriptor instead.
func (*FrameResponse) Descriptor() ([]byte, []int) {
	return file_koala_inference_proto_rawDescGZIP(), []int{3}
}

func (x *FrameResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *FrameResponse) GetDetections() []*Detection {
	if x != nil {
		return x.Detections
	}
	return nil
}

type BatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Frames        []*FrameRequest        `protobuf:"bytes,2,rep,name=frames,proto3" json:"frames,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchRequest) Reset() {
	*x = BatchRequest{}
	mi := &file_koala_inference_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchRequest) ProtoMessage() {}

func (x *BatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koala_inference_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchRequest.ProtoReflect.Descriptor instead.
func (*BatchRequest) Descriptor() ([]byte, []int) {
	return file_koala_inference_proto_rawDescGZIP(), []int{4}
}

func (x *BatchRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *BatchRequest) GetFrames() []*FrameRequest {
	if x != nil {
		return x.Frames
	}
	return nil
}

type BatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ModelVersion  string                 `protobuf:"bytes,1,opt,name=model_version,json=modelVersion,proto3" json:"model_version,omitempty"`
	Responses     []*FrameResponse       `protobuf:"bytes,2,rep,name=responses,proto3" json:"responses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchResponse) Reset() {
	*x = BatchResponse{}
	mi := &file_koala_inference_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchResponse) ProtoMessage() {}

func (x *BatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koala_inference_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchResponse.ProtoReflect.Descriptor instead.
func (*BatchResponse) Descriptor() ([]byte, []int) {
	return file_koala_inference_proto_rawDescGZIP(), []int{5}
}

func (x *BatchResponse) GetModelVersion() string {
	if x != nil {
		return x.ModelVersion
	}
	return ""
}

func (x *BatchResponse) GetResponses() []*FrameResponse {
	if x != nil {
		return x.Responses
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_koala_inference_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_koala_inference_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_koala_inference_proto_rawDescGZIP(), []int{6}
}

type HealthResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Status  string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Version string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	// contract_version reported by the worker. Orchestrator checks this matches.
	ContractVersion string `protobuf:"bytes,3,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_koala_inference_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_koala_inference_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_koala_inference_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *HealthResponse) GetContractVersion() string {
	if x != nil {
		return x.ContractVersion
	}
	return ""
}

var File_koala_inference_proto protoreflect.FileDescriptor

const file_koala_inference_proto_rawDesc = "" +
	"\n" +
	"\x15koala_inference.proto\x12\x12koala.inference.v1\"P\n" +
	"\x04BBox\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x02R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x02R\x06height\"\xd1\x01\n" +
	"\tDetection\x12\x1b\n" +
	"\tcamera_id\x18\x01 \x01(\tR\bcameraId\x12\x17\n" +
	"\azone_id\x18\x02 \x01(\tR\x06zoneId\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05label\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x02R\n" +
	"confidence\x12,\n" +
	"\x04bbox\x18\x05 \x01(\v2\x18.koala.inference.v1.BBoxR\x04bbox\x12*\n" +
	"\x11timestamp_unix_ms\x18\x06 \x01(\x03R\x0ftimestampUnixMs\"\xd3\x01\n" +
	"\fFrameRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1b\n" +
	"\tcamera_id\x18\x02 \x01(\tR\bcameraId\x12\x17\n" +
	"\azone_id\x18\x03 \x01(\tR\x06zoneId\x12\x14\n" +
	"\x05frame\x18\x04 \x01(\fR\x05frame\x12-\n" +
	"\x13captured_at_unix_ms\x18\x05 \x01(\x03R\x10capturedAtUnixMs\x12)\n" +
	"\x10contract_version\x18\x06 \x01(\tR\x0fcontractVersion\"s\n" +
	"\rFrameResponse\x12#\n" +
	"\rmodel_version\x18\x01 \x01(\tR\fmodelVersion\x12=\n" +
	"\n" +
	"detections\x18\x02 \x03(\v2\x1d.koala.inference.v1.DetectionR\n" +
	"detections\"g\n" +
	"\fBatchRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\x06frames\x18\x02 \x03(\v2 .koala.inference.v1.FrameRequestR\x06frames\"u\n" +
	"\rBatchResponse\x12#\n" +
	"\rmodel_version\x18\x01 \x01(\tR\fmodelVersion\x12?\n" +
	"\tresponses\x18\x02 \x03(\v2!.koala.inference.v1.FrameResponseR\tresponses\"\x0f\n" +
	"\rHealthRequest\"m\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12)\n" +
	"\x10contract_version\x18\x03 \x01(\tR\x0fcontractVersion2\x92\x02\n" +
	"\x0fInferenceWorker\x12S\n" +
	"\fAnalyzeFrame\x12 .koala.inference.v1.FrameRequest\x1a!.koala.inference.v1.FrameResponse\x12S\n" +
	"\fAnalyzeBatch\x12 .koala.inference.v1.BatchRequest\x1a!.koala.inference.v1.BatchResponse\x12U\n" +
	"\fWorkerHealth\x12!.koala.inference.v1.HealthRequest\x1a\".koala.inference.v1.HealthResponseB0Z.github.com/baresystems/koala/proto/inferencev1b\x06proto3"

var (
	file_koala_inference_proto_rawDescOnce sync.Once
	file_koala_inference_proto_rawDescData []byte
)

func file_koala_inference_proto_rawDescGZIP() []byte {
	file_koala_inference_proto_rawDescOnce.Do(func() {
		file_koala_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_koala_inference_proto_rawDesc), len(file_koala_inference_proto_rawDesc)))
	})
	return file_koala_inference_proto_rawDescData
}

var file_koala_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_koala_inference_proto_goTypes = []any{
	(*BBox)(nil),           // 0: koala.inference.v1.BBox
	(*Detection)(nil),      // 1: koala.inference.v1.Detection
	(*FrameRequest)(nil),   // 2: koala.inference.v1.FrameRequest
	(*FrameResponse)(nil),  // 3: koala.inference.v1.FrameResponse
	(*BatchRequest)(nil),   // 4: koala.inference.v1.BatchRequest
	(*BatchResponse)(nil),  // 5: koala.inference.v1.BatchResponse
	(*HealthRequest)(nil),  // 6: koala.inference.v1.HealthRequest
	(*HealthResponse)(nil), // 7: koala.inference.v1.HealthResponse
}
var file_koala_inference_proto_depIdxs = []int32{
	0, // 0: koala.inference.v1.Detection.bbox:type_name -> koala.inference.v1.BBox
	1, // 1: koala.inference.v1.FrameResponse.detections:type_name -> koala.inference.v1.Detection
	2, // 2: koala.inference.v1.BatchRequest.frames:type_name -> koala.inference.v1.FrameRequest
	3, // 3: koala.inference.v1.BatchResponse.responses:type_name -> koala.inference.v1.FrameResponse
	2, // 4: koala.inference.v1.InferenceWorker.AnalyzeFrame:input_type -> koala.inference.v1.FrameRequest
	4, // 5: koala.inference.v1.InferenceWorker.AnalyzeBatch:input_type -> koala.inference.v1.BatchRequest
	6, // 6: koala.inference.v1.InferenceWorker.WorkerHealth:input_type -> koala.inference.v1.HealthRequest
	3, // 7: koala.inference.v1.InferenceWorker.AnalyzeFrame:output_type -> koala.inference.v1.FrameResponse
	5, // 8: koala.inference.v1.InferenceWorker.AnalyzeBatch:output_type -> koala.inference.v1.BatchResponse
	7, // 9: koala.inference.v1.InferenceWorker.WorkerHealth:output_type -> koala.inference.v1.HealthResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_koala_inference_proto_init() }
func file_koala_inference_proto_init() {
	if File_koala_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_koala_inference_proto_rawDesc), len(file_koala_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_koala_inference_proto_goTypes,
		DependencyIndexes: file_koala_inference_proto_depIdxs,
		MessageInfos:      file_koala_inference_proto_msgTypes,
	}.Build()
	File_koala_inference_proto = out.File
	file_koala_inference_proto_goTypes = nil
	file_koala_inference_proto_depIdxs = nil
}
