# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: koala_inference.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'koala_inference.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15koala_inference.proto\x12\x12koala.inference.v1\";\n\x04\x42\x42ox\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\r\n\x05width\x18\x03 \x01(\x02\x12\x0e\n\x06height\x18\x04 \x01(\x02\"\x95\x01\n\tDetection\x12\x11\n\tcamera_id\x18\x01 \x01(\t\x12\x0f\n\x07zone_id\x18\x02 \x01(\t\x12\r\n\x05label\x18\x03 \x01(\t\x12\x12\n\nconfidence\x18\x04 \x01(\x02\x12&\n\x04\x62\x62ox\x18\x05 \x01(\x0b\x32\x18.koala.inference.v1.BBox\x12\x19\n\x11timestamp_unix_ms\x18\x06 \x01(\x03\"\x8c\x01\n\x0c\x46rameRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x11\n\tcamera_id\x18\x02 \x01(\t\x12\x0f\n\x07zone_id\x18\x03 \x01(\t\x12\r\n\x05\x66rame\x18\x04 \x01(\x0c\x12\x1b\n\x13\x63\x61ptured_at_unix_ms\x18\x05 \x01(\x03\x12\x18\n\x10\x63ontract_version\x18\x06 \x01(\t\"Y\n\rFrameResponse\x12\x15\n\rmodel_version\x18\x01 \x01(\t\x12\x31\n\ndetections\x18\x02 \x03(\x0b\x32\x1d.koala.inference.v1.Detection\"T\n\x0c\x42\x61tchRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x30\n\x06\x66rames\x18\x02 \x03(\x0b\x32 .koala.inference.v1.FrameRequest\"\\\n\rBatchResponse\x12\x15\n\rmodel_version\x18\x01 \x01(\t\x12\x34\n\tresponses\x18\x02 \x03(\x0b\x32!.koala.inference.v1.FrameResponse\"\x0f\n\rHealthRequest\"K\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x18\n\x10\x63ontract_version\x18\x03 \x01(\t2\x92\x02\n\x0fInferenceWorker\x12S\n\x0c\x41nalyzeFrame\x12 .koala.inference.v1.FrameRequest\x1a!.koala.inference.v1.FrameResponse\x12S\n\x0c\x41nalyzeBatch\x12 .koala.inference.v1.BatchRequest\x1a!.koala.inference.v1.BatchResponse\x12U\n\x0cWorkerHealth\x12!.koala.inference.v1.HealthRequest\x1a\".koala.inference.v1.HealthResponseB-Z+github.com/barelabs/koala/proto/inferencev1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'koala_inference_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z+github.com/barelabs/koala/proto/inferencev1'
  _globals['_BBOX']._serialized_start=45
  _globals['_BBOX']._serialized_end=104
  _globals['_DETECTION']._serialized_start=107
  _globals['_DETECTION']._serialized_end=256
  _globals['_FRAMEREQUEST']._serialized_start=259
  _globals['_FRAMEREQUEST']._serialized_end=399
  _globals['_FRAMERESPONSE']._serialized_start=401
  _globals['_FRAMERESPONSE']._serialized_end=490
  _globals['_BATCHREQUEST']._serialized_start=492
  _globals['_BATCHREQUEST']._serialized_end=576
  _globals['_BATCHRESPONSE']._serialized_start=578
  _globals['_BATCHRESPONSE']._serialized_end=670
  _globals['_HEALTHREQUEST']._serialized_start=672
  _globals['_HEALTHREQUEST']._serialized_end=687
  _globals['_HEALTHRESPONSE']._serialized_start=689
  _globals['_HEALTHRESPONSE']._serialized_end=764
  _globals['_INFERENCEWORKER']._serialized_start=767
  _globals['_INFERENCEWORKER']._serialized_end=1041
# @@protoc_insertion_point(module_scope)
